# Generated by Django 5.2.7 on 2025-10-19 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('usia', models.IntegerField()),
                ('alamat', models.TextField()),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_soal', models.TextField()),
                ('jawaban_benar', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_akhir', models.FloatField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eas.santri')),
            ],
        ),
        migrations.CreateModel(
            name='PilihanJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pilihan', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D')], max_length=1)),
                ('teks_pilihan', models.CharField(max_length=255)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='eas.soal')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_santri', models.CharField(max_length=1)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eas.santri')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eas.soal')),
            ],
        ),
    ]
