# Generated by Django 5.2.7 on 2025-10-24 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='santri',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eas.santri'),
        ),
    ]
