# Generated by Django 5.2.7 on 2025-10-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0002_alter_nilai_santri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilihanjawaban',
            name='kode_pilihan',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='soal',
            name='jawaban_benar',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
