# Generated by Django 5.2.7 on 2025-10-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0003_alter_pilihanjawaban_kode_pilihan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='santri_id',
            field=models.CharField(default='ARX000-00000', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='gender',
            field=models.CharField(choices=[('I', 'Ikhwan'), ('A', 'Akhwat')], max_length=1),
        ),
    ]
