# Generated by Django 5.2.7 on 2025-10-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0004_santri_santri_id_alter_santri_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluasi',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
