# Generated by Django 5.2.7 on 2025-10-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0006_santri_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='durasi_detik',
            field=models.IntegerField(default=0),
        ),
    ]
