# Generated by Django 5.2.7 on 2025-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas', '0007_nilai_durasi_detik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='durasi_detik',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
